DROP TABLE IF EXISTS "actions";
CREATE TABLE "actions" ("name" VARCHAR PRIMARY KEY  NOT NULL );
INSERT INTO "actions" VALUES('A_Main');
INSERT INTO "actions" VALUES('A_DeleteUserConfirmation');
INSERT INTO "actions" VALUES('A_SelectRoleToAssignActions');
INSERT INTO "actions" VALUES('A_SearchUsersByName');
INSERT INTO "actions" VALUES('A_SaveActionsForTheRole');
INSERT INTO "actions" VALUES('A_ReadRolesPaginated');
INSERT INTO "actions" VALUES('A_ReadActionsWithStatus');
INSERT INTO "actions" VALUES('A_CreateUser');
INSERT INTO "actions" VALUES('A_Authorize');
INSERT INTO "actions" VALUES('A_UpdateUser');
INSERT INTO "actions" VALUES('A_Authenticate');
INSERT INTO "actions" VALUES('A_CreateRoleForm');
INSERT INTO "actions" VALUES('A_UpdateUserForm');
INSERT INTO "actions" VALUES('A_Null');
INSERT INTO "actions" VALUES('A_DeleteUser');
INSERT INTO "actions" VALUES('A_CreateUserForm');
INSERT INTO "actions" VALUES('A_SelectUserToAssignRoles');
INSERT INTO "actions" VALUES('A_UpdateActions');
INSERT INTO "actions" VALUES('A_ReadAllUsers');
INSERT INTO "actions" VALUES('A_ReadRolesWithStatus');
INSERT INTO "actions" VALUES('A_UpdateRoleForm');
INSERT INTO "actions" VALUES('A_SearchActionsByName');
INSERT INTO "actions" VALUES('A_Logout');
INSERT INTO "actions" VALUES('A_SaveRolesForTheUser');
INSERT INTO "actions" VALUES('A_DeleteRoleConfirmation');
INSERT INTO "actions" VALUES('A_SearchRolesByName');
INSERT INTO "actions" VALUES('A_CreateRole');
INSERT INTO "actions" VALUES('A_UpdateRole');
INSERT INTO "actions" VALUES('A_ReadUsersPaginated');
INSERT INTO "actions" VALUES('A_ReadAllRoles');
INSERT INTO "actions" VALUES('A_DeleteRole');
DROP TABLE IF EXISTS "roles";
CREATE TABLE "roles" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL  UNIQUE , "description" VARCHAR);
INSERT INTO "roles" VALUES(1,'Administrator','Administrative user, has access to everything.');
INSERT INTO "roles" VALUES(2,'Login','Login privileges, granted after account confirmation.');
INSERT INTO "roles" VALUES(3,'Accounting','Mostly access to accounting information.');
DROP TABLE IF EXISTS "roles_actions";
CREATE TABLE "roles_actions" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "role_id" INTEGER NOT NULL , "action_name" VARCHAR NOT NULL );
INSERT INTO "roles_actions" VALUES(262,2,'A_Authenticate');
INSERT INTO "roles_actions" VALUES(263,2,'A_Authorize');
INSERT INTO "roles_actions" VALUES(264,2,'A_ReadUsersPaginated');
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL  UNIQUE , "password" VARCHAR NOT NULL );
INSERT INTO "users" VALUES(1,'admin','$2y$10$A1RLqTO8SHxQeuhl/ps/I.I6cstHfT0PPdl1CPVOQo/FVQMeL2h2.');
INSERT INTO "users" VALUES(18,'test01','$2y$10$KSGtiHiFu3h3qHdGWf4xge7PFtRKAWFnrcgqHEPSL9gwCViE9EKY2');
INSERT INTO "users" VALUES(19,'test02','$2y$10$UTE5c5fRkkX7zj/qekCvAOfP.roe4KK73HLKUO5HF4FVoIQ0T3QGm');
INSERT INTO "users" VALUES(20,'test03','$2y$10$9XSGVXgQYU5L.voP9r3KFedhnkq7MaBzbelav9SSUJZfV66nrXtkq');
INSERT INTO "users" VALUES(21,'test04','$2y$10$U34xUNho1tm2a1s7eqhPOubOTtWppnSmm9.Lq6qWTqZ3DcB9Rpt4u');
INSERT INTO "users" VALUES(22,'test05','$2y$10$MsLr3Rkp/A55MCpMgVpVu.WERDUgwVn1z8su56ZLcm3vzQV2M.ctC');
INSERT INTO "users" VALUES(23,'test06','$2y$10$BGeDz1TC0CJURONpBkTvVug9GbvPaip8W4g0oooTsZ3irzln2vDL6');
INSERT INTO "users" VALUES(24,'test07','$2y$10$OWIL7lIdRmygswgcPRFWOO1Ow14ZFHjGsTIX2Aw8x1ehwloOuNx52');
INSERT INTO "users" VALUES(25,'test08','$2y$10$rQFbTVEbTCPbFWH93e0cq.YBw6S34bP.gZc4TQ3vtBeM3ZK6cbhhO');
INSERT INTO "users" VALUES(26,'test09','$2y$10$x0qi5GhvNb9cy2ucRyKLNOiYdVVEJAIvv3duE4W5nGVPnIJrjwdOy');
INSERT INTO "users" VALUES(27,'test10','$2y$10$yGk8gRVZ10yt6guAqojRRe/WKItobNX3yc73QfrvFh.H2NeLA7WKi');
DROP TABLE IF EXISTS "users_roles";
CREATE TABLE "users_roles" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "user_id" INTEGER NOT NULL , "role_id" INTEGER NOT NULL );
INSERT INTO "users_roles" VALUES(59,1,1);
INSERT INTO "users_roles" VALUES(81,5,2);
INSERT INTO "users_roles" VALUES(82,15,2);
INSERT INTO "users_roles" VALUES(85,18,2);
